decision/urls.py
from django.urls import path
from . import views

app_name = 'decision'
urlpatterns = [
  path('', views.index, name='index'),
  path('new/', views.new, name='new'),
  path('create/', views.create, name='create'),
  path('show/<str:activity_id>', views.show, name='show'),
  path('vote/<str:activity_id>', views.vote, name='vote'),
  path('success/<str:activity_id>', views.success, name="success"),
  path('admin/<str:admin_token>', views.admin, name='admin'),
  path('update/<str:activity_id>', views.update, name='update'),
  path('delete/<str:activity_id>', views.delete, name='delete')
]

decision_maker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('decision.urls'))
]

decision/models.py
import uuid
from django.db import models
import random

def __generate_token__():
  l = '1234567890qwertyuiopasdfghjklzxcvbnm'
  token = ""
  for i in range(8):
    x = random.randint(0, len(l) - 1)
    token += l[x]
  return token

class Activity(models.Model):
  context = models.CharField(max_length=50)
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  creator = models.CharField(max_length=20)
  email = models.CharField(max_length=20)
  admin_token = models.TextField(default=__generate_token__())
  description = models.TextField(default='Do you think this is a greate idea?')
  expire_on = models.DateField()
  def __str__(self):
    return self.context

class Choice(models.Model):
  activity_id = models.ForeignKey(Activity, on_delete=models.CASCADE)
  name = models.CharField(max_length=100, unique=True)
  votes_count = models.IntegerField(default=0)
  def __str__(self):
    return self.name

decision/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.urls import reverse
from django.core.mail import send_mail
import json
import datetime

from .models import Activity

def index(request):
  return render(request, 'decision/index.html')

def new(request):
  return render(request, 'decision/new.html')

def create(request):
  context = request.POST['context']
  creator = request.POST['creator']
  email = request.POST['email']
  description = request.POST['description']
  options_list = request.POST.getlist('option')
  expire_on = timezone.now() + datetime.timedelta(days=7)

  new_activity = Activity(context=context, creator=creator, email=email, description=description, expire_on=expire_on)
  new_activity.save()

  for i in range(len(options_list)):
    option = options_list[i]
    new_activity.choice_set.create(name=option)

  message = {
    'title': 'Cіз сауалнама құрдыңыз',
    'content': 'Құпия сілтеме сізге электрондық пошта арқылы жіберілді. Сіз білуі керек адамдарға сілтеме жібере аласыз. Дауыс беру сессиясы аяқталған күні жабық болады'
  }

#пока не работает :(
  send_mail(
      'Сауалнама',
      f'Сіз құрған сауалнама {new_activity.context}, сіздің админ токеніңіз {new_activity.admin_token}, сіздің сауалнамаға сілтеме: localhost:8000/show/{new_activity.id} ',
      'md@md.com',
      [email,],
      fail_silently=True,
  )

  return render(request, 'decision/info.html', {'message': message})

def show(request, activity_id):
  activity = Activity.objects.get(pk=activity_id)
  choice_list = activity.choice_set.all()
  return render(request, 'decision/show.html', {'activity': activity, 'choice_list': choice_list})

def vote(request, activity_id):
  activity = Activity.objects.get(pk=activity_id)
  choice_list = activity.choice_set.all()
  try:
    selected_choice = activity.choice_set.get(name=request.POST['choice'])
  except (KeyError, Choice.DoesNotExist):
    return render(request, 'decision/show.html', {'activity': activity, 'choice_list': choice_list, 'error_message': 'You did not select anything'})
  else:
    selected_choice.votes_count += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse('decision:success', args=(activity.id,)))

def success(request, activity_id):
  activity = Activity.objects.get(pk=activity_id)
  choice_list = list(activity.choice_set.all().values('name', 'votes_count'))

  success_message = f'Дауыс бергеніңіз үшін рахмет. Соңғы нәтижелер {activity.expire_on} күні шығарылады'
  return render(request, 'decision/success.html', {'choice_list': choice_list, 'activity': activity, 'message': success_message})

def admin(request, admin_token):
  activity = get_object_or_404(Activity, admin_token=admin_token)
  choice_list = list(activity.choice_set.all().values('name', 'votes_count'))
  if request.GET['email'] == activity.email:
    return render(request, 'decision/admin.html', {'activity': activity, 'choice_list': choice_list})
  else:
    return HttpResponse('Denied! You do not have access')

def update(request, activity_id):
  activity = get_object_or_404(Activity, pk=activity_id)

  old_choice_list = activity.choice_set.all()
  new_choice_list = request.POST.getlist('option')

  for old_choice in old_choice_list:
    try:
      new_choice_list.index(old_choice.name)
    except:
      old_choice.delete()

  for new_choice in new_choice_list:
    try:
      choice = activity.choice_set.get(name=new_choice)
    except:
      if new_choice != '':
        activity.choice_set.create(name=new_choice)

  
  choice_list = activity.choice_set.all()
  
  success_message = 'Сіз сауалнамаңызды жаңартыңыз'

  send_mail(
      'Сауалнама',
      'Сіздің сауалнамаңыз жаңартылды!',
      'md@md.com',
      [email,],
      fail_silently=True,
  )
  return render(request, 'decision/success.html', {'activity': activity, 'choice_list': choice_list, 'message': success_message})


def delete(request, activity_id):
  activity = get_object_or_404(Activity, pk=activity_id)
  activity_context = activity.context
  activity.delete()

  send_mail(
      'Сауалнама',
      f'Сіздің \'{activity_context}\' сауалнамаңыз жойылды. Соңымен бірге дауыстар да жойылды',
      'md@md.com',
      [email,],
      fail_silently=True,
  )

  message = {
    'title': 'Cіз сауалнамаңызды жойдыңыз',
    'content': 'Сіз сауалнамаңызды жойдыңыз, дауыстар жойылды'
  }
  return render(request, 'decision/info.html', {'message': message})

decision/templates/decision/admin.html
{% include './partials/_header.html' %}

{% load static %}

<div class="glass hidden"></div>

<h3 class="admin-title">Төменде сіздің сауалнамаңыз туралы ақпарат берілген: {{ activity.context }}</h3>
<main class="admin-page">
    <form class="pure-form pure-form-aligned edit" action="{% url 'decision:update' activity.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <div class="pure-control-group">
                <label>Сауалнама</label>
                <input name="context" type="text" value="{{ activity.context }}" required>
            </div>
    
            <div class="pure-control-group">
                <label>Сипаттамасы</label>
                <textarea name="description">{{ activity.description }}</textarea>
            </div>
    
            <div class="options">
              {% for choice in choice_list %}
                <div class="pure-control-group">
                    <label>Option </label>
                    <input name="option" type="text" value="{{choice.name}}">
                </div>
              {% endfor %}

            </div>
            <div class="button-group">
                <button type="submit" class="pure-button pure-button-primary">Сауалнаманы жаңарту</button>
                <button type="button" class="pure-button pure-button-primary" id="add-option">Опция қосу</button>
                <a type="button" class="pure-button pure-button-primary" id="to-delete-confirm" >Сауалнаманы жою</a>
            </div>
        </fieldset>
    </form>

    <div class="delete hidden">
        <form action="{% url 'decision:delete' activity.id %}" method="POST">
            {% csrf_token %}
            <h3>Ескерту: сауалнаманы артқа қайтару мүмкін емес</h3>
            <button class="pure-button delete-btn">Жою</button>
            <a class="pure-button back-btn">Шығу</a>
        </form>
    </div>

    <div class="admin-chart">
        <table class="pure-table pure-table-horizontal">
            <thead>
                <tr>
                    <th>Опциялар</th>
                    <th>Дауыстар</th>
                </tr>
            </thead>
        
            <tbody>
              {% for choice in choice_list %}
              <tr>
                  <td>{{ choice.name }}</td>
                  <td>{{ choice.votes_count }}</td>
              </tr>
              {% endfor %}
              <tr>
                <td colspan='2'>
                    <canvas id="barChart"></canvas>
                </td>
              </tr>
            </tbody>
        </table>
    </div>
</main>  
    <script>
    var ctx = document.getElementById("barChart").getContext('2d');
    
    var choice_list = "{{ choice_list }}"
    choice_list = choice_list.replace(/&#39;/g, "\"")
    choice_list = JSON.parse(choice_list)
    console.log(choice_list)
    var labels = [];
    var data = []
    
    
    choice_list.forEach(function(choice){
      labels.push(choice.name);
      data.push(choice.votes_count)
    })
    
    var myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels,
            datasets: [{
                label: '# of Votes',
                data,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
    });     
    </script>

    <script src="{% static 'decision/javascript/admin.js'%}"></script>
{% include './partials/_footer.html' %}

decision/templates/decision/index.html
{% load static %}

<html>
  <head>
    <title>MD</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'decision/style/index.css' %}">
  </head>
  <body>
    <div class="info">
      <h1>Ең жақсын таңдау үшін дауыс бер</h1>
      <div>
        <a href="{% url 'decision:new' %}">Құру</a>
        <a id="vote-btn">Дауыс беру</a>
        <a id="admin-btn">Сауалнамалар</a>
      </div>
      <p>Әр пікір біз үшін маңызды</p>
    </div>

    <div class="glass hidden"></div>
    <div class="background">
      <div></div>
      <div></div>
      <div></div>
    </div>

    <div class="token hidden">
      <h3>Сіздің сауалнама токеніңіз?</h3>
      <input type="text" id="activity-token" placeholder="Token">
      <a href="" id="activity-token-link">Қатысу</a>
    </div>

    <div class="admin hidden">
      <form id="admin-token-link" method='GET'>
        <h3>Админ токені</h3>
        <input type="text" id="admin-token" placeholder="Token">
        <input type="email" name="email" placeholder="example@example.com">
        <button>Сауалнаманы өзгерту</button>
      </form>
    </div>


    <script src="{% static 'decision/javascript/index.js'%}"></script>
  </body>
</html>

decision/templates/decision/info.html
{% include './partials/_header.html' %}
{% load static %}

<main class="info">
  <h1>{{ message.title }}</h1>
  <p>{{ message.content }}</p>
  <a class="pure-button pure-button-primary" href="{% url 'decision:index' %}">Ok!</a>
</main>

<script>
  window.setTimeout(function () {
    location.href = "{% url 'decision:index' %}";
}, 5000); 
</script>

{% include './partials/_footer.html' %}

decision/templates/decision/new.html
{% include './partials/_header.html' %}

{% load static %}
<form class="pure-form pure-form-aligned new" action="{% url 'decision:create' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <div class="pure-control-group">
            <label>Сауалнама</label>
            <input name="context" type="text" placeholder="Қандай сауалнама жасағыңыз келеді?" required>
        </div>

        <div class="pure-control-group">
            <label>Есіміңіз</label>
            <input name="creator" type="text" placeholder="Бұл есім көрінеді" required>
        </div>

        <div class="pure-control-group">
            <label>Поштаңыз</label>
            <input name="email" type="email" placeholder="Хабарлама келетін пошта" required>
        </div>

        <div class="pure-control-group">
            <label>Сипаттамасы</label>
            <textarea name="description" placeholder="Сауалнама сипаттамасы"></textarea>
        </div>

        <div class="options">
            <div class="pure-control-group">
                <label>Опция:</label>
                <input name="option" type="text" placeholder="Опция">
            </div>
            <div class="pure-control-group">
                <label>Опция:</label>
                <input name="option" type="text" placeholder="Опция">
            </div>
            <div class="pure-control-group">
                <label>Опция:</label>
                <input name="option" type="text" placeholder="Опция">
            </div>
        </div>
        <div class="button-group">
            <button type="submit" class="pure-button pure-button-primary create">Сауалнама құру</button>
            <button type="button" class="pure-button pure-button-primary" id="add-option">Опция қосу</button>
        </div>
    </fieldset>
</form>

<script src="{% static 'decision/javascript/addOption.js'%}"></script>

{% include './partials/_footer.html' %}

decision/templates/decision/partials/_footer.html
</body>
</html>

decision/templates/decision/partials/_header.html
{% load static %}

<html>
  <head>
    <title>MD</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js"></script>

    <link rel='stylesheet' href="{% static 'decision/style/header.css' %}">
    <link rel='stylesheet' href="{% static 'decision/style/new.css' %}">
    <link rel='stylesheet' href="{% static 'decision/style/show.css' %}">
    <link rel='stylesheet' href="{% static 'decision/style/success.css' %}">
    <link rel='stylesheet' href="{% static 'decision/style/admin.css' %}">
    <link rel='stylesheet' href="{% static 'decision/style/info.css' %}">
  </head>
  <body>
      <div class="pure-menu pure-menu-horizontal nav">
          <ul class="pure-menu-list">
              <li class="pure-menu-item"><a href="#" class="pure-menu-link">MD</a></li>
              <li class="pure-menu-item"><a href="#" class="pure-menu-link">Құру</a></li>
              <li class="pure-menu-item"><a href="#" class="pure-menu-link">Дауыс беру</a></li>
              <li class="pure-menu-item"><a href="#" class="pure-menu-link">Бізбен хабарласу</a></li>
          </ul>
      </div>

decision/templates/decision/show.html
{% include './partials/_header.html' %}

<main class="show">
    <table class="pure-table pure-table-bordered">
        <thead>
            <tr>
                <th>Сауалнама</th>
                <th>Жасаушы</th>
                <th>Email</th>
                <th>Қолданылу мерзімі</th>
            </tr>
        </thead>
    
        <tbody>
            <tr>
                <td>{{ activity.context }}</td>
                <td>{{ activity.creator }}</td>
                <td>{{ activity.email }}</td>
                <td>{{ activity.expire_on }}</td>
            </tr>
            <tr>
                <th colspan="4">Сауалнама сипаттамасы</th>
            </tr>
            <tr>
              <td colspan="4">{{ activity.description }}</td>
            </tr>
            <tr>
              <th colspan="4">Келесі біреуін тандаңыз</th>
            </tr>
            <tr>
              <td colspan="4">
                  <form class="pure-form" action="{% url 'decision:vote' activity.id %}" method="POST">
                      {% csrf_token %}
                      {% for choice in choice_list %}
                        <label class="pure-checkbox">
                            <input name="choice" type="radio" value="{{ choice }}">
                            {{ choice }}
                        </label>
                      {% endfor %}
                      <p><strong>* Сіздің деректеріңіз жасырын түрде жиналады</strong></p>
                      <button class="pure-button pure-button-primary">Дауыс беру</button>
                      <a href="{% url 'decision:index' %}" class="pure-button pure-button-active">Бас тарту</a>
                  </form>
              </td>
            </tr>
        </tbody>
    </table>
</main>

{% include './partials/_footer.html' %}

decision/templates/decision/success.html
{% include './partials/_header.html' %}

<div class="graph">
    <p class="message">{{ message }}</p>
    <p>Дауыс берудің қазіргі нәтижелері</p>
    <table class="pure-table pure-table-horizontal">
        <thead>
            <tr>
                <th>Опциялар</th>
                <th>Дауыстар</th>
            </tr>
        </thead>
    
        <tbody>
          {% for choice in choice_list %}
          <tr>
              <td>{{ choice.name }}</td>
              <td>{{ choice.votes_count }}</td>
          </tr>
          {% endfor %}
          <tr>
            <td colspan='2'>
                <canvas id="myChart"></canvas>
            </td>
          </tr>
        </tbody>
    </table>
    <a class="pure-button pure-button-primary" href="{% url 'decision:index' %}">Шығу</a>
</div>

<script>
var ctx = document.getElementById("myChart").getContext('2d');

var choice_list = "{{ choice_list }}"
choice_list = choice_list.replace(/&#39;/g, "\"")
choice_list = JSON.parse(choice_list)
console.log(choice_list)
var labels = [];
var data = []


choice_list.forEach(function(choice){
  labels.push(choice.name);
  data.push(choice.votes_count)
})

var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels,
        datasets: [{
            label: '# of Votes',
            data,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
});

</script>


{% include './partials/_footer.html' %}